# Generated by Django 2.2.3 on 2019-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='encoding',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='label',
            field=models.IntegerField(),
        ),
    ]
